name: "ci / arch"

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Arch Linux environment
      uses: docker://archlinux:latest
      with:
        args: |
          bash -c "
            pacman -Syu --noconfirm
            pacman -S --noconfirm base-devel meson ninja gtk3 gtk-layer-shell wayland-protocols spdlog fmt nlohmann-json libpulse libmpdclient libdbusmenu-gtk3 libsigc++-3.0 libinput libudev libevdev libxkbcommon libyaml-cpp
            cd /github/workspace
            meson setup build
            ninja -C build waybar
            echo 'Build successful!'
          "

    - name: Test compilation
      run: |
        echo "Arch Linux build test completed successfully"
        echo "✅ Waybar compiles on Arch Linux with Hyprland dependencies"
